Andres ruiz tarea 7
emolinaglobant/academy-react pull request #212
Opened 2022-02-14 21:17 UTC by andresCruiz

2022-02-15 13:00 UTC, emolinaglobant requested changes
@andresCruiz , i don't see the unit tests for "tarea-7"

also why tarea-3 so late?

2022-02-15 13:00 UTC, emolinaglobant commented on Andres-ruiz/tarea-3/oddOrEven.js
> +function oddOrEven(array) {
@andresCruiz , make this  a one line solution

2022-02-15 13:00 UTC, emolinaglobant commented on Andres-ruiz/tarea-3/largestPairSum.js
> + function largestPairSum (numbers) {
@andresCruiz , make this  a one line solution

2022-02-15 13:00 UTC, emolinaglobant commented on Andres-ruiz/tarea-3/DuplicateSandwich.js
> +function duplicateSandwich(arr) {
@andresCruiz , make this  a one line solution

2022-02-15 13:00 UTC, emolinaglobant commented on Andres-ruiz/tarea-4/js/index.js
> +botonesNumeros.forEach(boton => {
@andresCruiz , use english as main language for programming

2022-02-18 14:03 UTC, emolinaglobant commented
@andresCruiz where are the unit tests?

2022-02-18 15:17 UTC, andresCruiz commented on Andres-ruiz/tarea-4/js/index.js
> +botonesNumeros.forEach(boton => {
this  solution is in another branch

2022-02-24 01:25 UTC, emolinaglobant commented
@SebastianRuedaGlobant , you did not attend last comment

2022-02-24 01:25 UTC, closed without merging