Tarea 11
emolinaglobant/academy-react pull request #228
Opened 2022-02-17 01:32 UTC by santiagoGuillenGlob

2022-02-21 12:41 UTC, emolinaglobant requested changes

2022-02-21 12:41 UTC, emolinaglobant commented on santiao-guillen/homework-11/to-do-list-router/src/Components/Homework2.js
> +const Homework2 = () => {
@santiagoGuillenGlob , this approach is really wrong, your basically repeating the code in different components, you should use only one Homework component and pass props with the info to it

2022-02-21 12:41 UTC, emolinaglobant commented on santiao-guillen/homework-11/to-do-list-router/src/Components/Navegation.js
> +                <ul>
@santiagoGuillenGlob , this list should be dynamic and come from an Array

2022-02-21 12:41 UTC, emolinaglobant commented on santiao-guillen/homework-11/to-do-list-router/src/Components/Navegation.js
> +                <Route path="/Homework-1" element={<Homework1 />} />
@santiagoGuillenGlob , same here

2022-02-28 13:53 UTC, emolinaglobant commented
@santiagoGuillenGlob the task list is not working

2022-02-28 22:43 UTC, santiagoGuillenGlob commented
because i used the node server for a create a fake api, where a stay save the task, You can run the server whit npm run server

2022-02-28 22:43 UTC, santiagoGuillenGlob commented
This is error?

2022-03-18 16:00 UTC, closed without merging