Tarea 4
emolinaglobant/academy-react pull request #97
Opened 2022-01-28 02:34 UTC by OlmeiroOrozco

Task 4: I tried to work with modules js.

2022-01-31 20:06 UTC, emolinaglobant commented
@OlmeiroOrozco , this looks a lot like @juan-hm solution

2022-01-31 20:26 UTC, OlmeiroOrozco commented
In fact, I based it on the following repo: https://github.com/accesibleprogramacion/calculadora. 
And I tried to change it with modules and separate things as it should be: in HTML only HTML and the respective changes with Javascript.

I'm sure that we worked under the same example.

2022-02-01 19:01 UTC, emolinaglobant requested changes

2022-02-01 19:01 UTC, emolinaglobant commented on olmeiro-orozco/tarea-4/results.js
> +    // console.log(type);
@OlmeiroOrozco , please remove console logs

2022-02-01 19:01 UTC, emolinaglobant commented on olmeiro-orozco/tarea-4/calculator.js
> +  multiply(num1, num2) {
@OlmeiroOrozco , make sure all class methods are alphabetically sorted

2022-02-01 19:01 UTC, emolinaglobant commented on olmeiro-orozco/tarea-4/results.js
> +    // console.log(number);
@OlmeiroOrozco , remove console logs

2022-02-01 19:01 UTC, emolinaglobant commented on olmeiro-orozco/tarea-4/results.js
> +    this.showOldValue = showOldValue;
@OlmeiroOrozco , none of these properties are defined as class members

2022-02-02 14:44 UTC, emolinaglobant approved these changes

2022-02-02 14:44 UTC, merged